### ISSUE TITLE
Maybe wrong voxel spacing

### ISSUE THREAD

**Issue by dgrat** [angeloskath/simple-3dviz#2]
The voxel spacing is unequal for assymetric models. 

![screeny](https://user-images.githubusercontent.com/4668178/98441663-128ed800-2100-11eb-88b2-a044f0ed740e.png)

```
import numpy as np

from simple_3dviz import Spherecloud
from simple_3dviz.renderables import Mesh
from simple_3dviz.behaviours.movements import CameraTrajectory
from simple_3dviz.behaviours.misc import LightToCamera
from simple_3dviz.behaviours.io import SaveFrames
from simple_3dviz.behaviours.trajectory import Circle
from simple_3dviz.window import show
from simple_3dviz.utils import render


if __name__ == "__main__":
    arr_vox = np.fromfile("/home/varg/vox4/Result/hex_david_lowres.raw", dtype=np.bool)
    arr_vox_3d = np.reshape(arr_vox, (42,41,64), order='F')

    show(
        Mesh.from_voxel_grid(voxels=arr_vox_3d, colors=(0.5,0.5,0.5), sizes=(0.005,0.005,0.005)),
        light=(-1, -1, 1),
        behaviours=[
            CameraTrajectory(
                Circle(center=(0, 0, 0), point=(1, -1, 0), normal=(0, 0, -1)),
                speed=0.0004)
        ],
        size=(1024, 1024)
    )
```

[hex_david_lowres.zip](https://github.com/angeloskath/simple-3dviz/files/5504742/hex_david_lowres.zip)

**Comment by dgrat** [comment]
I think for 10x10x10 cubes it looks right, but not for other models I tested.

**Comment by dgrat** [comment]
Also the sizes parameter looks wrong. The voxels just seem to overlap if you make them taller.

**Comment by angeloskath** [comment]
Hi Daniel,

I understand that this is a ridiculously late reply, however better late than never.

The issue here is a miscommunication from our part of what exactly is `from_voxel_grid` doing. You assume that `from_voxel_grid` just positions that many voxels of a given size in the scene. However, what is actually happening is, the centroids are positioned (based on the boolean matrix) in the volume provided by the bbox parameter (see https://github.com/angeloskath/simple-3dviz/blob/ef2dacc36430677558e8836c0ccec345da6e8895/simple_3dviz/renderables/mesh.py#L475). Then the sizes can be used to control the sizes of the boxes at those positions.

If the sizes are not provided then they are selected such that the cover almost the entire space.

You can also see our [docs](https://simple-3dviz.com/data_loading/#creating-voxel-grids) for the intended use of `from_voxel_grid`.

If in your case you want the boxes to have fixed size regardless of the number of boxes present, then you need to change the volume that they occupy by providing the `bbox` parameter as follows:

```python
import numpy as np
from simple_3dviz import Mesh
from simple_3dviz.window import show

# or np.ones((N, N, N), dtype=np.bool) if you want to see the whole box
def heart_voxel_grid(N):
    x = np.linspace(-1.3, 1.3, N)
    y = np.linspace(-1.3, 1.3, N)
    z = np.linspace(-1.3, 1.3, N)
    x, y, z = np.meshgrid(x, y, z)
    return (2*x**2 + y**2 + z**2-1)**3 - (1/10) * x**2*z**3 - y**2*z**3 < 0

# Let's position the first voxel grid at [-0.7, -0.7. -0.7] to [0.3, 0.3, 0.3]
m1 = Mesh.from_voxel_grid(heart_voxel_grid(16), bbox=[[-0.7, -0.7, -0.7], [0.3, 0.3, 0.3]])

# and let's position the second one that has half the number of voxels at each size from
# [0.3, 0.3, 0.3] to [0.8, 0.8, 0.8], namely half the size of the bbox as well
m2 = Mesh.from_voxel_grid(heart_voxel_grid(8), bbox=[[0.3, 0.3, 0.3], [0.8, 0.8, 0.8]])

# notice that both shapes have voxels of exactly the same size
show([m1, m2])
```

I will close the issue but feel free to reopen it if you want. Hopefully, next time you won't have to wait half a year for an answer :-).

Cheers,
Angelos
