### ISSUE TITLE
3D load texture

### ISSUE THREAD

**Issue by jgonzalezdemendibil** [angeloskath/simple-3dviz#4]
Hello:

I have succesfully loaded an .obj model as in the example but I can not import the .mtl to apply the texture. 
¿Could you please give me an example of the implementation?

**Comment by angeloskath** [comment]
Hi,

We must update our documentation indeed. The support for textures is provided with `TexturedMesh` instead of `Mesh`.

The most minimal example would be the following:

```python
from simple_3dviz import TexturedMesh
from simple_3dviz.window import show

# Search the .mtl file in the same directory as the mesh file
m = TexturedMesh.from_file("/path/to/obj")
show(m)

# Load an .mtl file that is given explicitly
m = TexturedMesh.from_file("/path/to/obj", "/path/to/mtl")
show(m)
```
Keep in mind that `TexturedMesh` only supports a single material for the whole mesh, which means that multi material meshes must be split manually into multiple meshes (sorry for that).

Cheers,
Angelos

**Comment by jgonzalezdemendibil** [comment]
Hi,

Thanks for your fast answer. I have tried the exmaple above an works perfectly!

Javi
